### ISSUE TITLE
Phase out Math.random()

### ISSUE THREAD

**Issue by vibornoff** [amartov/PassGenJS#3]
https://github.com/amartov/PassGenJS/blob/master/PassGenJS.js#L30-L33

Should be replaced with `window.crypto.gatRandomValues()`

**Comment by vibornoff** [comment]
Also note that pointing range of the desired random values is error-prone due to non-uniform distribution of the resulting value. To make the values fit into the range you should do something similar to:

``` js
function rand ( min, max ) {
    var r, mask = ceil_to_the_next_power_of_2( max - min );
    do { r = getRandomNumber() & mask } while ( r >= max - min );
    return min + r;
}
```

**Comment by EvgeniyRRU** [comment]
But 

``` javascript
window.crypto.gatRandomValues()
```

works only in modern browsers. See https://developer.mozilla.org/en-US/docs/Web/API/RandomSource.getRandomValues
We should to use something else.

**Comment by vibornoff** [comment]
Yep, though you have no option to change this.

`Math.random()` output isn't of cryptographic quality anyway. Overall entropy of passwords generated with `PassGen` will never exceed the entropy of the `Math.random()`'s internal state. Check this up: [Why is Google Chrome's Math.random number generator not _that_ random?](http://stackoverflow.com/questions/9550796/why-is-google-chromes-math-random-number-generator-not-that-random).

I had to write own `window.crypto.getRandomValues()` implementation for my [asmcrypto.js](https://github.com/vibornoff/asmcrypto.js) project. Read the [whole PRNG thread](https://github.com/vibornoff/asmcrypto.js/issues/27) for more detailed explaination.

You have only 2 options:
- either implement your own fallback `getRandomValues` method for old browsers and have a deal with entropy collection (which is not trivial though)
- or drop support of dumb browsers.

I strongly suggest the last thing.
